# Generated by Django 3.1.1 on 2020-10-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_distance_coefficient_driver_pay_size_coefficient_time_coefficient_weight_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
