# Generated by Django 3.1.1 on 2020-10-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20201008_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='international',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='scope',
            field=models.CharField(default='national', max_length=13),
            preserve_default=False,
        ),
    ]
