# Generated by Django 3.1.1 on 2020-10-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_cargo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo_picture',
            name='cargo_picture',
            field=models.ImageField(blank=True, upload_to='media/cargo_images'),
        ),
    ]
